### ISSUE TITLE
Nutrient Ranges

### ISSUE THREAD

**Issue by philip-sterne** [minerva-university/rationapp#12]
Here are the updated limits for nutrients:

**Total Concentrate %:**
 This should be calculated as Total Concentrate DM / Total DM.

**Calcium (Ca):**

Dry Cows:
Minimum: 0.35% of Dry Matter (DM)
Maximum: 0.55% of DM
Lactating Cows:
Minimum: 0.7% of DM
Maximum: 1.0% of DM

**Phosphorus (P):**

Dry Cows:
Minimum: 0.25% of DM
Maximum: 0.40% of DM
Lactating Cows:
Minimum: 0.35% of DM
Maximum: 0.45% of DM
Neutral Detergent Fiber (NDF):

**Total Diet NDF:**
Minimum: 28% of DM
Maximum: 35% of DM

**Crude Protein (CP):**

Dry Cows:
Minimum: 12% of DM
Maximum: 14% of DM
Lactating Cows:
Minimum: 16% of DM
Maximum: 18% of DM
Energy (Dry Matter Intake - DMI):

**Standard Rule for Energy Provision:**
Minimum: 95% of the energy requirement
Maximum: 105% of the energy requirement

1. Please update the [spreadsheet](https://docs.google.com/spreadsheets/d/18fyLZTodSiMOmZkrjskX6ampLC0NX7MybSj9uZQwUeU/edit?usp=sharing), so that the warning ranges respect these values.
2. Please update the code so that these ranges are respected. (eg. I see that: CP intake of 0%, Ca intake of 0%, and P intake of 0% are currently all accepted in the code.)

**Comment by SomtochiUmeh** [comment]
@philip-sterne I don't understand the energy calculation `Total Concentrate DM / Total DM`. Is this the formula for `Concentrate intake (Max)`? If yes, what will be the range?

**Comment by philip-sterne** [comment]
> @philip-sterne I don't understand the energy calculation `Total Concentrate DM / Total DM`. Is this the formula for `Concentrate intake (Max)`? If yes, what will be the range?

The range is 0%-60%. 

Please look at the blocks B29:I30 for the [feed](https://docs.google.com/spreadsheets/d/18fyLZTodSiMOmZkrjskX6ampLC0NX7MybSj9uZQwUeU/edit?usp=sharing) spreadsheet. These blocks have all the warning ranges.
