### ISSUE TITLE
Small UI tweaks

### ISSUE THREAD

**Issue by philip-sterne** [minerva-university/rationapp#13]
1. Please change "Volume (kg)" to "Milk volume per day (kg)" (on the Cow characteristics page)
2. Please add "NDF intake" as one of the requirements (on the Cow Requirements page). Both as a Requirement (at the top), and as a total (at the bottom).
3. Please add "Concentration intake (Max)" as one of the requirements (on the Cow Requirements page). Both as a Requirement (at the top), and as a total (at the bottom).

**Comment by SomtochiUmeh** [comment]
`Concentrate intake (Max)` and `NDF intake` have fixed values in the sheet - no calculations. Should I just use the fixed values?

**Comment by SomtochiUmeh** [comment]
Oh, is `Total Concentrate DM / Total DM` the calculation for `Concentrate intake (Max)`?
