### ISSUE TITLE
Nikki 

### ISSUE THREAD

**Issue by Nikkiapp** [minerva-university/rationapp#18]
Hi my apologies i just looked at the concentrate list and seen that it is incomplete, I have uploaded here the excel doc , could you please just use the fodder and concentrate list from this excel file to update the app.

- on the feed formulation page could you please make the formulation diet table headings in line with the cow requirements meaning the DM, CP etc lines up for easy reading.
- in the feeding guidelines there is an error 
[240827 ration calculator latest ver 01.xlsx](https://github.com/user-attachments/files/16758865/240827.ration.calculator.latest.ver.01.xlsx)
with the dry cow requirements , the CP should be 12% please correct this .
- the paw prints can you change the icon into a cow instead .
if you need more clarification don't hesitate to drop me an email.

Kind regards 
Nikki

**Comment by SomtochiUmeh** [comment]
Hey @Nikkiapp,
For the given cow characteristics, CP is 16% same as the sheet. Is this what I should change to 12%?

<table>
<tr>
<td><img src="https://github.com/user-attachments/assets/59ac588a-600e-4134-a46d-76ee0b3ddbfe" width="250"></td>
<td><img src="https://github.com/user-attachments/assets/3f540978-9782-4bf6-91ad-774a67e87259" width="250"></td>
</tr>
</table>

![image](https://github.com/user-attachments/assets/27a32276-6bf5-4f61-9464-69f6ef5c0159)

**Comment by Nikkiapp** [comment]
Hi Somto the CP that you need to change is the Dry cow feeding recommendations under feeding guidelines

**Comment by SomtochiUmeh** [comment]
> on the feed formulation page could you please make the formulation diet table headings in line with the cow requirements meaning the DM, CP etc lines up for easy reading

working on this now... I'm not sure how this will look since the Fodder and Concentrate sections have 2 more columns (the ingredient name and Fresh feed intake (kg/d) than the Totals section. what's a visually appealing way to make them align?

**Comment by SomtochiUmeh** [comment]
- Change rationapp app name to RationApp
- Change app icon from Flutter to Cow icon
- Landscape doesn't scroll for FeedFormula page

**Comment by philip-sterne** [comment]
- Add button to calculate optimal feed.  (Chat to me about the linear programming initialization, and function call. See here for a basic example: https://github.com/minerva-university/rationapp/blob/d11869ca1d7cf05e26dac271a192d55667530697/lib/utils/testing.dart#L9)
